apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-pod
  template:
    metadata:
      name: db-pod
      labels:
        app: db-pod
    spec:
      containers:
        - name: db-container
          image: aluracursos/mysql-db:1
          ports:
            - containerPort: 3306
          envFrom:  
            - configMapRef:
                name: db-cf
