apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-deployment
spec:
  template:
    metadata:
      name: portal-pod
      labels:
        app: portal-pod
    spec:
      containers:
        - name: portal-container
          image: aluracursos/portal-noticias:1
          ports: 
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-cf
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 10
          resources:
            requests:
              cpu: 10m
  replicas: 3
  selector:
    matchLabels:
      app: portal-pod
