apiVersion: v1
kind: Pod
metadata:
  name: portal-pod
  labels:
    app: portal-pod

spec:
  containers:
    - name: portal-container
      image: aluracursos/portal-noticias:1
      ports: 
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: portal-cf
