apiVersion: v1
kind: Pod
metadata:
  name: sistema-pod
  labels:
    app: sistema-pod
spec:
  containers:
    - name:  sistema-pod-container
      image: aluracursos/sistema-noticias:1
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: sistema-cf
  